model:
  encoder: 'vitb'
  features: 128
  out_channels: [96, 192, 384, 768]

transform:
  ToTensor:
  Resize:
    width: 518
    height: 518
    resize_target: False
    keep_aspect_ratio: True
    ensure_multiple_of: 14.0
    resize_method: 'lower_bound'
  Normalize: 
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]